apiVersion: apps/v1
kind: Deployment
metadata:
  name: rails-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rails-app
  template:
    metadata:
      labels:
        app: rails-app
    spec:
      containers:
      - name: rails-app
        image: ridwan3030/railsapp:latest  # change to your image
        ports:
        - containerPort: 3000
        env:
        - name: DATABASE_HOST
          value: "postgres"
        - name: DATABASE_USERNAME
          value: "user"
        - name: DATABASE_PASSWORD
          value: "password"
        - name: DATABASE_NAME
          value: "myapp_development"

