apiVersion: v1
kind: Service
metadata:
  name: rails-service
spec:
  type: NodePort
  selector:
    app: rails-app
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 32000  # Use a port between 30000-32767


