apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rails-app
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  source:
    repoURL: https://github.com/yourusername/rails-app
    targetRevision: HEAD
    path: argocd-app.yaml/k8s
  project: default
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
