apiVersion: apps/v1
kind: Deployment
metadata:
  name: rails-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rails-app
  template:
    metadata:
      labels:
        app: rails-app
    spec:
      containers:
      - name: rails
        image: ridwan3030/rails-app:latest
        ports:
        - containerPort: 3000
        env:
        - name: DATABASE_HOST
          value: postgres
        - name: DATABASE_USER
          value: rails_user
        - name: DATABASE_NAME
          value: rails_db
        - name: DB_PASSWORD
          value: secret
        volumeMounts:
        - name: db-config
          mountPath: /app/config/database.yml
          subPath: database.yml  # <-- Must match the key in ConfigMap
      volumes:
      - name: db-config
        configMap:
          name: rails-db-config
