apiVersion: v1
kind: ConfigMap
metadata:
  name: rails-db-config
data:
  database.yml: |
    default: &default
      adapter: postgresql
      encoding: unicode
      pool: 5
      username: <%= ENV["DATABASE_USER"] %>
      password: <%= ENV["DB_PASSWORD"] %>
      host: <%= ENV["DATABASE_HOST"] %>

    development:
      <<: *default
      database: <%= ENV["DATABASE_NAME"] %>
